### ISSUE TITLE
Incorrect parameter on chart deployment

### ISSUE THREAD

**Issue by alexppg** [rancher/local-path-provisioner#140]
The helm chart adds the parameter `--service-account-name` which seems to not exist, since the pod fails with the error `Critical error: flag provided but not defined: -service-account-name`. What could be the fix?

**Comment by bclermont** [comment]
The problem is that, the service account flag had been added [in this commit](https://github.com/rancher/local-path-provisioner/commit/b44b2c3b5d18772aa306d3fb1210b202c353ef09) on August 29.

But the chart use image `0.0.17`(https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.17) released 14 Aug.

So, the helm chart is for a unreleased version of the app.

In the [docker registry](https://hub.docker.com/r/rancher/local-path-provisioner/tags), there is no images for nightly, or snapshots.

This chart is basically broken

**Comment by bclermont** [comment]
I just built and publish a docker image `bclermont/local-path-provisioner:b821f90-amd64` and the chart works now

**Comment by alexppg** [comment]
This can be closed since there's updated images.
