### ISSUE TITLE
Support for the volume capacity limitations

### ISSUE THREAD

**Issue by YanekR** [rancher/local-path-provisioner#225]
Hi, 

I currently start using lpp for sorting out mounts in optane disks as a cache, I was wondering if capacity limitations will be implemented. Currently lack of limitations might cause a cluster crashes what would not be acceptable in my solution. 

Would you be able to provide any estimated timeframe for implementing this feature?

Thanks,
Jan

**Comment by derekbit** [comment]
You can check the `example/quota` to see if it fits your expectation. But it only support `xfs`.

**Comment by aragilar** [comment]
`ext4` since linux 5.4 supports project quotas like `xfs` (which appears to be how the example `xfs` quota support works). `btrfs` seems to support quotas on subvolumes (which would seem to match the behaviour that's desired). Is there any reason the `xfs` support didn't become the default, and is currently an example, other than other file systems didn't have support at that time?
