### ISSUE TITLE
How to re-use existing PVC?

### ISSUE THREAD

**Issue by ap1969** [rancher/local-path-provisioner#26]
Hi,
I've got this working in my set up, where the PVC is created on the node, in a mounted block storage, located at /mnt/dev_primary_lon1

However, the PVC is created in a UUID-based folder:
/mnt/dev_primary_lon1/pvc-xxxxxxx

If the node is somehow destroyed, but data should be save as it's on the block storage. But if I were to re-spin-up a new node, is there any way to point it to the existing PVC?

Or to simply create a pvc with a defined name in the first place?

Regards,
Andy

**Comment by yasker** [comment]
If the node is down, PVC object in Kubernetes shouldn't be affected since it's stored in the etcd.

If the directory still exists somehow, you should able to manually create a hostpath type PV with node selector to point to the directory, then bound it with the PVC you want to use. Check the PV and PVC created by local path provisioner for examples.

**Comment by huyouba1** [comment]
Hello!
If the node where the pv is located is unavailable for some reason, the data made at the application software level is highly available, and the pod is started at the new node for data migration.
Then how to bind the old pvc to the node where the new pv is located, and how to guarantee the pod data of StatefulSet.
We know that StatefulSet is started orderly, 0-1-2-3 If the node where Pod1 is located is unavailable, consider how to migrate the PV data of the node where Pod1 is located. How to not affect the start of pod?
