### ISSUE TITLE
Compatibility with Kubernetes 1.11

### ISSUE THREAD

**Issue by fabiorauber** [rancher/local-path-provisioner#3]
Is it possible for this to work on Kubernetes 1.11? Support for K8S 1.12 is still experimental in Rancher v2.1.1

**Comment by yasker** [comment]
The v0.0.1 release was made for Kubernetes v1.11 (which requires some extra configuration to enable an alpha feature gate). Unfortunately Kubernetes breaks backward compatibility with v1.12 release, so it's hard for us to support both v1.11 and v1.12. That's the reason we dropped support for v1.11.

You can still try to use v0.0.1 release with Kubernetes v1.11. The last known working version with v1.11 is at https://github.com/rancher/local-path-provisioner/tree/5010718979a72f7fca6cc59fc444b1a0911ff72e , and you will need to use the deployment files in this commit (instead of in the README.md which always pointed to the latest). But it's not supported and recommended. Rancher will soon start support v1.12, which should make things easier.

**Comment by fabiorauber** [comment]
Thanks for the reply! I've just upgraded my Rancher installation to v2.1.2 and decided to upgrade my Kubernetes cluster to version 1.12 as well, and all worked out fine. The volumes are being dynamically created now.

I've developed a Helm chart for local-path-provisioner. I would be glad to make a PR for this if you think it would help. 
https://github.com/interlegis/il-charts/tree/master/local-path-provisioner

**Comment by aojea** [comment]
@yasker any chance to add/support the helm chart mentioned by @fabiorauber to the repo?
I think that it will improve the UX

**Comment by yasker** [comment]
@aojea oh sure, I missed that.

@fabiorauber Thanks for the chart! Can you make a PR to `/deploy/chart`? Thanks!

**Comment by davidkarlsen** [comment]
@fabiorauber will you do a PR? Of course there's no problem using your chart - but I find it always favourable to keep the chart alongside the sw.

**Comment by amrecio** [comment]
Hello. I found this issue a few days ago. I didn't know about @fabiorauber's Helm chart, but coincidentally, I was already working on a chart for internal use in the company I work for. I submitted PR #28 as an alternative because as far as I know, @fabiorauber hasn't replied in a while. Feel free to accept or reject it.

**Comment by fabiorauber** [comment]
Sorry everyone for not responding to this issue's comments. These days I needed to revisit our local-path-provisioner installation, and decided to make a Rancher Chart out of the official chart that was initially contributed by @amrecio, migrating it to Helm v3 as well. Published a PR in rancher/charts repo (https://github.com/rancher/charts/pull/856)
