### ISSUE TITLE
feature: add support to set folderName on PVC

### ISSUE THREAD

**Issue by vvanouytsel** [rancher/local-path-provisioner#384]
Whenever a PV is dynamically created, a directory is generated with the following name `$persistentVolumeName_$persistentVolumeClaimNamespace_$persistentVolumeClaimName`.

It would be helpful if we can decide what the directory name of the generated directory would be up front. This could be done by setting an annotation on the persistent volume claim.

```yaml
annotations:
  folderName: fooBar
```

This logic is included in the following PR:
https://github.com/rancher/local-path-provisioner/pull/372

**Comment by XtraLarge** [comment]
It would be great to consider this also automatically in the provisioner, something like use the namespace of the pvc for automatic sort the PV in folders.

In my scenario I have four k3s-nodes in a lxc container on one proxmox server. They all share one datadir where local-path autoprovision the pvs. This datadir is quit confusing because of the flat use of the volid.

**Comment by senpro-ingwersenk** [comment]
Seconding this.

I finished bootstrapping a k3s cluster for a client and getting to the storage paths is a bit confusing. Not impossible, but it very much is not a whole lot of fun. For my own deployment at home, I plan to use the shared filesystem together with a permanent rclone mount, which I access from many locations. Being able to "predict" the name would be very helpful here when I need to dig into log files or the like.

Thanks!

**Comment by lizhifengones** [comment]
To reconsider this point.
For example, we can mount different disks for different PVs to achieve IO isolation.

**Comment by lizhifengones** [comment]
@derekbit PTAL
Are we still accepting any features?
