### ISSUE TITLE
Should contrllor run as statefulset instead of deployment?

### ISSUE THREAD

**Issue by liyimeng** [rancher/local-path-provisioner#75]
Citing from here:

https://arslan.io/2018/06/21/how-to-write-a-container-storage-interface-csi-plugin/

> For the Controller plugin, we could deploy it as a StatefulSet. Most people associate StatefulSet with a persistent storage. But it’s more powerful. A StatefulSet also comes with scaling guarantees. This means we could use the Controller plugin as a StatefulSet and set the replicas field to 1. This would give us a stable scaling, that means that if the pod dies or we do an update, it never creates a second pod before the first one is fully shutdown and terminated. This is very important, because this guarantees that only a single copy of the Controller plugin will run.

What do you think @yasker ?

**Comment by yasker** [comment]
Local path provisioner has the ability to scale and use the leader election mechanism to ensure only one process at any given time is in charge of the provisioning. In the HA scenario, if the leader failed due to any reason, the other provisioners will pick up the request. So we don't need to make sure the scale must be 1.

**Comment by liyimeng** [comment]
Create thanks for the explanationm @yasker ! It is good that we already has this covered. ;)
