### ISSUE TITLE
Issue about pvc 

### ISSUE THREAD

**Issue by itsogkyc** [rancher/local-path-provisioner#82]
When pod is deleted , can pvc be deleted automatically?

**Comment by yasker** [comment]
PVC deletion is up to the user since it's persistent and has a lifecycle longer than the pod. PV can be deleted along with PVC is reclaimPolicy is `delete`. See https://kubernetes.io/docs/concepts/storage/persistent-volumes for details.

If you don't want persistent volume, you can use `emptyDir` instead.
