### ISSUE TITLE
local-path-provisioner doesn't work on clusters without internet

### ISSUE THREAD

**Issue by iirekm** [rancher/local-path-provisioner#84]
Fixing Helm chart is easy: add HELPER_IMAGE with env var to point to the proper address of busybox.

But additionally imagePullSecrets has to be added to the create-xxxx pods generated by the provisioner and there's no way to do it.

**Comment by hwaastad** [comment]
@yasker this would be a minor change I think by extending the podpec in provisioner.go:
```
ImagePullSecrets: []v1.LocalObjectReference{
				{Name: p.pullSecret}, // should be loop of spec.imagepullsecrets
			},
```
We have met this issue our self having to use a private docker proxy.
I can add a PR for this one, but in my simple impl (since I have a limited knowledge of the go-client) I've added a pullproxy option to the provisioner (similar to the --helper-image). (Would probably be best if it was injected from the spec.imagepullsecrets from deployment,if possible)

**Comment by yasker** [comment]
Seems we should add an image pull secret option in the cmdline.

**Comment by vincent-herlemont** [comment]
If the PR https://github.com/rancher/local-path-provisioner/pull/119 is merged, this issue shouldn't be closed?
